import { useEffect, useMemo, useState } from 'react'
import { Building2, MapPin, Save, UserRound } from 'lucide-react'
import { useApp } from '../app/AppContext'
import { Button, ErrorState, StatusPill } from '../shared/ui'
export function AdvisorsPage(){
 const{boot,updateAdvisor,showToast,dataMode}=useApp();const[selectedId,setSelectedId]=useState(boot.advisors[0]?.id||''),advisor=boot.advisors.find(i=>i.id===selectedId)||boot.advisors[0]
 const[style,setStyle]=useState(advisor?.style||''),[audience,setAudience]=useState(advisor?.audience||''),[saving,setSaving]=useState(false),[error,setError]=useState(''),[savedAt,setSavedAt]=useState('')
 useEffect(()=>{setStyle(advisor?.style||'');setAudience(advisor?.audience||'')},[advisor?.id,advisor?.style,advisor?.audience])
 const example=useMemo(()=>`您好，我是${advisor?.store||'体验店'}的${advisor?.name||'顾问'}。针对${audience.split(/[、,，]/)[0]||'家庭用户'}，我会用${style||'真实、克制的方式'}说明体验重点，并先核验最新车型事实。`,[advisor,audience,style])
 async function save(){if(!advisor)return;setSaving(true);setError('');try{await updateAdvisor(advisor.id,{audience:audience.trim(),style:style.trim()});setSavedAt(new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'}));showToast(dataMode==='fallback'?'顾问画像已保存到当前浏览器的本地演示工作区':'顾问画像已保存到当前工作区')}catch(caught){setError(caught instanceof Error?caught.message:'画像保存失败')}finally{setSaving(false)}}
 return <section className="advisor-layout advisors-page"><aside className="advisor-directory"><div className="pane-toolbar"><div><strong>顾问目录</strong><small>{boot.advisors.length} 位顾问</small></div><StatusPill tone="demo">当前工作区</StatusPill></div>{boot.advisors.map(item=><button data-testid={`advisor-row-${item.id}`} key={item.id} className={advisor?.id===item.id?'advisor-row active':'advisor-row'} onClick={()=>{setSelectedId(item.id);setError('')}}><span className="avatar">{item.name.slice(0,1)}</span><span><strong>{item.name}</strong><small>{item.store}</small></span><em>{item.model_focus}</em></button>)}</aside>{advisor?<main className="advisor-editor"><header><span className="avatar large">{advisor.name.slice(0,1)}</span><div><h2>{advisor.name}</h2><p><Building2 size={14}/>{advisor.store} · <MapPin size={14}/>{advisor.city}</p></div></header><div className="advisor-facts"><div><span>主要车型</span><strong>{advisor.model_focus}</strong></div><div><span>从业时间</span><strong>{advisor.experience_years} 年</strong></div><div><span>常用平台</span><strong>{advisor.platforms.join('、')}</strong></div></div><label className="field-label">主要服务客群<textarea data-testid="advisor-audience" value={audience} onChange={e=>setAudience(e.target.value)}/></label><label className="field-label">表达方式<textarea data-testid="advisor-style" value={style} onChange={e=>setStyle(e.target.value)}/></label>{error?<ErrorState description={error}/>:null}<div className="advisor-save-bar"><span>{savedAt?`最近保存 ${savedAt}`:'修改仅影响当前工作区'}</span><Button data-testid="save-advisor" loading={saving} disabled={!audience.trim()||!style.trim()} onClick={()=>void save()}><Save size={16}/>保存画像</Button></div></main>:null}<aside className="advisor-preview"><div className="pane-toolbar"><strong>画像影响预览</strong><StatusPill tone="info">实时</StatusPill></div><section><UserRound size={18}/><div><strong>参与生成的字段</strong><p>服务客群、表达方式、主要车型、常用平台。</p></div></section><section><strong>示例表达</strong><blockquote>{example}</blockquote></section><section><strong>边界说明</strong><p>不使用年龄、性别等敏感属性推断客户，也不会自动覆盖顾问人工修改。</p></section></aside></section>
}
