import { useState } from 'react'
import { AlertTriangle, ArrowUpRight, Clock3, UserRoundPlus } from 'lucide-react'
import { api } from '../api'
import { useApp } from '../app/AppContext'
import { Button, Dialog, EmptyState, StatusPill } from '../shared/ui'

export function CustomerRiskPage(){
 const{workspace,boot,dataMode,refreshWorkspace,updateEnterpriseLocal,showToast}=useApp();const items=workspace.enterprise.customer_risks;const[selectedId,setSelectedId]=useState(items[0]?.id||'');const[selectedAction,setSelectedAction]=useState('');const[note,setNote]=useState('');const[working,setWorking]=useState(false);const selected=items.find(i=>i.id===selectedId)||items[0]
 async function act(action:string,actionNote=''){if(!selected)return;setWorking(true);try{if(dataMode==='fallback')updateEnterpriseLocal(current=>({...current,customer_risks:current.customer_risks.map(item=>item.id===selected.id?{...item,status:action,updated_at:new Date().toISOString(),note:actionNote}:item),promises:action==='create_promise'?[{id:`local-risk-promise-${Date.now()}`,customer_id:selected.customer_id,advisor_id:current.customer_profiles.find(c=>c.id===selected.customer_id)?.advisor_id||'',original_message:selected.reason,commitment:selected.recommended_action,due_at:selected.due_at,completion_criteria:'顾问提交处理结果',status:'pending_confirmation',source:'客户风险转承诺',created_at:new Date().toISOString(),remind_at:'',overdue:false,manager_attention:true,evidence:selected.evidence,demo_flag:true},...current.promises]:current.promises}));else{await api.customerRiskAction(selected.id,action,actionNote);await refreshWorkspace()}showToast('客户风险处理状态已更新并保留原因');setSelectedAction('');setNote('')}catch(error){showToast(error instanceof Error?error.message:'客户风险处理失败')}finally{setWorking(false)}}
 if(!selected)return <EmptyState title="暂无客户风险" description="未解决问题、承诺超时和试驾后未跟进会进入这里。"/>
 const customer=workspace.enterprise.customer_profiles.find(i=>i.id===selected.customer_id);const advisor=boot.advisors.find(item=>item.id===customer?.advisor_id)
 const needNote=(action:string)=>['false_positive','assign_manager','assign_advisor','snooze'].includes(action)
 function choose(action:string){if(needNote(action)){setSelectedAction(action);setNote('')}else void act(action)}
 return <section className="enterprise-split-layout risk-page" data-testid="customer-risks"><aside className="enterprise-list-pane"><div className="pane-toolbar"><strong>需要经理关注</strong><span>{items.length}</span></div><div className="compact-queue">{items.map(item=><button key={item.id} className={selected.id===item.id?'compact-row active':'compact-row'} onClick={()=>setSelectedId(item.id)}><span><strong>{workspace.enterprise.customer_profiles.find(c=>c.id===item.customer_id)?.name||item.customer_id}</strong><small>{item.reason}</small></span><StatusPill tone={item.level==='high'?'danger':'warning'}>{item.status}</StatusPill></button>)}</div></aside><main className="enterprise-detail-pane"><header className="detail-heading"><div><p className="eyebrow">客户经营风险 · {selected.demo_flag?'演示证据':'业务证据'}</p><h2>{customer?.name} · {selected.reason}</h2><p>{selected.impact}</p></div><StatusPill tone={selected.level==='high'?'danger':'warning'}>{selected.level}</StatusPill></header><section className="risk-evidence-list"><strong>原始证据</strong>{selected.evidence.map(item=><blockquote key={item}><AlertTriangle size={15}/>{item}</blockquote>)}</section><section><strong>负责人和建议</strong><p>当前负责人：{advisor?.name||customer?.advisor_id||'未分配'}</p><p>{selected.recommended_action}</p><small><Clock3 size={13}/>{selected.due_at} · {selected.manager_help?'建议经理介入':'顾问可自行处理'}</small></section><div className="demo-notice">风险来自可查看的证据，不使用无法解释的百分比分数；误报和关闭都必须保留人工原因。</div></main><aside className="enterprise-action-pane"><section className="action-stack"><strong>人工处理</strong><Button data-testid="risk-assign-manager" loading={working} onClick={()=>choose('assign_manager')}><UserRoundPlus size={16}/>转经理跟进</Button><Button onClick={()=>choose('assign_advisor')}>分配顾问</Button><Button onClick={()=>choose('create_followup')}><ArrowUpRight size={16}/>创建解释任务</Button><Button onClick={()=>choose('create_promise')}>创建承诺</Button><Button variant="secondary" onClick={()=>choose('false_positive')}>标记误报</Button><Button variant="secondary" onClick={()=>choose('snooze')}>稍后处理</Button><Button variant="secondary" onClick={()=>choose('resolve')}>关闭风险</Button></section><section><strong>当前状态</strong><p>{selected.status}</p><small>{selected.updated_at||'尚未处理'}</small></section></aside><Dialog open={Boolean(selectedAction)} title="填写处理原因" description="该原因会保存在当前工作区的审计记录中。" onClose={()=>setSelectedAction('')} testId="risk-action-dialog" footer={<><Button variant="secondary" onClick={()=>setSelectedAction('')}>取消</Button><Button data-testid="confirm-risk-action" loading={working} disabled={!note.trim()} onClick={()=>void act(selectedAction,note)}>确认</Button></>}><label className="field-label">处理说明<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="说明分配、稍后处理或误报的依据。"/></label></Dialog></section>
}
