import { useState } from 'react'
import { AlertTriangle, ArrowUpRight, Clock3, UserRoundPlus } from 'lucide-react'
import { api } from '../api'
import { useApp } from '../app/AppContext'
import { Button, EmptyState, StatusPill } from '../shared/ui'

export function CustomerRiskPage(){
 const{workspace,dataMode,refreshWorkspace,updateEnterpriseLocal,showToast}=useApp();const items=workspace.enterprise.customer_risks;const[selectedId,setSelectedId]=useState(items[0]?.id||'');const selected=items.find(i=>i.id===selectedId)||items[0]
 async function act(action:string){if(!selected)return;if(dataMode==='fallback')updateEnterpriseLocal(current=>({...current,customer_risks:current.customer_risks.map(item=>item.id===selected.id?{...item,status:action,updated_at:new Date().toISOString()}:item)}));else{await api.customerRiskAction(selected.id,action);await refreshWorkspace()}showToast('客户风险处理状态已更新')}
 if(!selected)return <EmptyState title="暂无客户风险" description="未解决问题、承诺超时和试驾后未跟进会进入这里。"/>
 const customer=workspace.enterprise.customer_profiles.find(i=>i.id===selected.customer_id)
 return <section className="enterprise-split-layout risk-page" data-testid="customer-risks"><aside className="enterprise-list-pane"><div className="pane-toolbar"><strong>需要经理关注</strong><span>{items.length}</span></div><div className="compact-queue">{items.map(item=><button key={item.id} className={selected.id===item.id?'compact-row active':'compact-row'} onClick={()=>setSelectedId(item.id)}><span><strong>{workspace.enterprise.customer_profiles.find(c=>c.id===item.customer_id)?.name||item.customer_id}</strong><small>{item.reason}</small></span><StatusPill tone={item.level==='high'?'danger':'warning'}>{item.status}</StatusPill></button>)}</div></aside><main className="enterprise-detail-pane"><header className="detail-heading"><div><p className="eyebrow">客户经营风险 · {selected.demo_flag?'演示证据':'业务证据'}</p><h2>{customer?.name} · {selected.reason}</h2><p>{selected.impact}</p></div><StatusPill tone={selected.level==='high'?'danger':'warning'}>{selected.level}</StatusPill></header><section className="risk-evidence-list"><strong>判断证据</strong>{selected.evidence.map(item=><blockquote key={item}><AlertTriangle size={15}/>{item}</blockquote>)}</section><section><strong>推荐动作</strong><p>{selected.recommended_action}</p><small><Clock3 size={13}/>{selected.due_at} · {selected.manager_help?'建议经理介入':'顾问可自行处理'}</small></section><div className="demo-notice">风险来自可查看的证据，不使用无法解释的百分比分数。</div></main><aside className="enterprise-action-pane"><section className="action-stack"><strong>人工处理</strong><Button data-testid="risk-assign-manager" onClick={()=>void act('assign_manager')}><UserRoundPlus size={16}/>指派经理</Button><Button onClick={()=>void act('create_followup')}><ArrowUpRight size={16}/>创建跟进任务</Button><Button variant="secondary" onClick={()=>void act('snooze')}>稍后处理</Button><Button variant="secondary" onClick={()=>void act('resolve')}>标记已解决</Button></section><section><strong>当前状态</strong><p>{selected.status}</p><small>{selected.updated_at||'尚未处理'}</small></section></aside></section>
}
