import { useState } from 'react'
import { AlertTriangle, DatabaseZap, RefreshCw, RotateCcw, ShieldCheck } from 'lucide-react'
import { api } from '../api'
import { useApp } from '../app/AppContext'
import { Button, StatusPill } from '../shared/ui'
import { navigate } from '../app/router'
import type { RoleSpace } from '../types'

export function GovernancePage(){
 const{workspace,dataMode,refreshWorkspace,updateEnterpriseLocal,showToast}=useApp();const[working,setWorking]=useState('')
 async function sync(name:string){setWorking(name);try{if(dataMode==='fallback')updateEnterpriseLocal(current=>({...current,sync_events:[{id:`sync-${Date.now()}`,integration:name,mode:'demo',status:'completed',summary:`${name} Demo Adapter 完成模拟同步`,created_at:new Date().toISOString(),details:{records:3}},...current.sync_events],enterprise_meta:{...current.enterprise_meta,last_sync_at:new Date().toISOString()}}));else{await api.syncIntegration(name);await refreshWorkspace()}showToast('模拟同步已完成')}catch(error){showToast(error instanceof Error?error.message:'模拟同步失败')}finally{setWorking('')}}
 async function retry(eventId:string){setWorking(eventId);try{if(dataMode==='fallback')updateEnterpriseLocal(current=>({...current,sync_events:current.sync_events.map(item=>item.id===eventId?{...item,status:'success',retry_count:(item.retry_count||0)+1,retried_at:new Date().toISOString(),summary:`重试成功：${item.summary}`}:item)}));else{await api.retrySyncEvent(eventId,'治理页面人工重试');await refreshWorkspace()}showToast('失败同步事件已重试')}catch(error){showToast(error instanceof Error?error.message:'重试失败')}finally{setWorking('')}}
 async function scenario(id:string){setWorking(id);try{if(dataMode==='fallback')updateEnterpriseLocal(current=>({...current,enterprise_meta:{...current.enterprise_meta,demo_scenario:id,current_role:id==='knowledge-change'?'hq':id==='quality-coaching'||id==='promise-overdue'?'manager':'advisor'}}));else{await api.resetScenario(id);await refreshWorkspace()}const role=(id==='knowledge-change'||id==='best-practice'?'hq':id==='quality-coaching'||id==='promise-overdue'?'manager':'advisor') as RoleSpace;navigate(role==='hq'?'hotspots':role==='manager'?'manager-radar':'today');showToast('当前工作区已切换到固定演示场景')}finally{setWorking('')}}
 return <section className="governance-page" data-testid="governance"><div className="governance-grid"><section><div className="section-heading"><strong>Demo Adapter</strong><span>未连接生产系统</span></div>{workspace.enterprise.integrations.map(item=><article key={item.name}><DatabaseZap size={18}/><div><strong>{item.label}</strong><p>{item.notice}</p><small>{item.record_count} 条结构化演示记录 · 未连接真实企业应用</small></div><StatusPill tone={item.ready?'success':'warning'}>{item.mode}</StatusPill><Button variant="secondary" loading={working===item.name} onClick={()=>void sync(item.name)}><RefreshCw size={14}/>模拟同步</Button></article>)}</section><section><div className="section-heading"><strong>演示场景切换器</strong><span>仅重置当前 workspace</span></div>{workspace.enterprise.demo_scenarios.map(item=><article key={item.id}><RotateCcw size={18}/><div><strong>{item.name}</strong><p>{item.description}</p></div><Button data-testid={`scenario-${item.id}`} variant="secondary" loading={working===item.id} onClick={()=>void scenario(item.id)}>进入场景</Button></article>)}</section></div><div className="governance-grid lower"><section><div className="section-heading"><strong>最近同步</strong><span>{workspace.enterprise.sync_events.length}</span></div>{workspace.enterprise.sync_events.slice(0,8).map(item=><article key={item.id} data-testid={`sync-event-${item.id}`}>{item.status==='failed'?<AlertTriangle size={16}/>:<RefreshCw size={16}/>}<div><strong>{item.summary}</strong><small>{item.integration} · {item.created_at}{item.retry_count?` · 已重试 ${item.retry_count} 次`:''}</small>{item.last_error?<p>{item.last_error}</p>:null}</div><StatusPill tone={item.status==='failed'?'danger':'success'}>{item.status}</StatusPill>{item.status==='failed'?<Button data-testid={`retry-sync-${item.id}`} variant="secondary" loading={working===item.id} onClick={()=>void retry(item.id)}>重试</Button>:null}</article>)}</section><section><div className="section-heading"><strong>审计日志</strong><span>{workspace.enterprise.audit_log.length}</span></div>{workspace.enterprise.audit_log.slice(0,12).map(item=><article key={item.id}><ShieldCheck size={16}/><div><strong>{item.action}</strong><p>{item.actor} · {item.role}</p><small>{item.object_type}/{item.object_id} · {item.created_at} · workspace {item.workspace_id.slice(0,8)}</small></div></article>)}</section></div></section>
}
